name: 'Ingest'
description: 'Ingest the thing'
inputs:
  style-name:
    description: 'Style name'
    required: false
  gcp-service-account-key:
    description: 'GCP service account key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
