name: Ad hoc ingest java 11

on:
  workflow_dispatch:
    inputs:
      repositoryToIngest:
        description: "Github organization/repository"
        required: true
      styleName:
        description: "Style name"
        required: false

jobs:
  ingest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Ingest
    steps:
      - name: Checkout repository to ingest
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.event.inputs.repositoryToIngest }}
      - name: ingest
        uses: docker://moderne/ingest:java11-latest
        env:
          MODERNE_API_ACCESS_TOKEN: ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
        with:
          args: --style-name ${{ github.event.inputs.styleName }}
      - name: Slack Notify on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS_WEBHOOK }}
          SLACK_USERNAME: moderne-ingest
          SLACK_COLOR: red
          SLACK_ICON: https://image.pngaaa.com/813/2886813-middle.png
          SLACK_TITLE: Ingest workflow failure
          SLACK_MESSAGE: We all have bad days
