name: Ad hoc ingest java 8

on:
  workflow_dispatch:
    inputs:
      repositoryToIngest:
        description: "Github organization/repository"
        required: true

jobs:
  ingest:
    runs-on: ubuntu-latest
    name: Ingest
    steps:
      - name: Checkout self
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout target
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repositoryToIngest }}
          path: target
      - name: Ingest
        uses: ./main/actions/java11
        id: ingest
        with:
          gcpKey: ${{ secrets.GCR_KEY }}
      - name: Slack Notify on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS_WEBHOOK }}
          SLACK_USERNAME: moderne-ingest
          SLACK_COLOR: red
          SLACK_TITLE: Ingest workflow failure
