---
name: Alluxio/alluxio ingest

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    paths:
      - "EMERGENCY-INGEST-1.md"
  workflow_dispatch: {}

jobs:
  ingest:
    uses: ./.github/workflows/_ingest.yml@main
    with:
      repository: Alluxio/alluxio
    secrets:
      moderne_api_access_token: ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
