name: qos-ch/logback ingest

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}

jobs:
  ingest:
    runs-on: ubuntu-latest
    name: Ingest
    steps:
      - name: Checkout self
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout target
        uses: actions/checkout@v2
        with:
          repository: qos-ch/logback
          path: target
      - name: Ingest
        uses: ./main/actions/java11
        id: ingest
        with:
          gcpKey: ${{ secrets.GCR_KEY }}
