name: spring-cloud/spring-cloud-config ingest

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}

jobs:
  ingest:
    runs-on: ubuntu-latest
    name: Ingest
    steps:
      - name: Checkout self
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout target
        uses: actions/checkout@v2
        with:
          repository: spring-cloud/spring-cloud-config
          path: target
      - name: Ingest
        uses: ./main
        id: ingest
        with:
          gcpKey: ${{ secrets.GCR_KEY }}
          styleName: spring